### ISSUE TITLE
Update Git Pages

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-docs#57]
At the last meeting, @cjjcastro brought MKDocs as a Jekyll alternative, which may bring advantages over the actual option.

So we need to set up all the current docs to match the MKDocs structure and up a Deploy with this technology on the GitPages

**Comment by cjjcastro** [comment]
I'm thinking of using mkdocs to generate our github pages. It is very simple to use

**Comment by cjjcastro** [comment]
here is the mkdocs documentation: [mkdocs](https://www.mkdocs.org/)

**Comment by cjjcastro** [comment]
I configured the pages with this theme: [mkdocs material](https://squidfunk.github.io/mkdocs-material/)

**Comment by cjjcastro** [comment]
can already be accessed at this link: [pages](https://cjjcastro.gitlab.io/2019-1-hubcare-docs/)

**Comment by cjjcastro** [comment]
Mkdocs github does not automatically deploy, so I had to configure a continuous integration tool.
Since we are using gitlab ci for the application, it has been chosen for this function.
the ```.gitlab-ci.yml``` file looks like this:
```
image: python:alpine

before_script:
  - pip install mkdocs
  # Add your custom theme if not inside a theme_dir
  # (https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes)
  - pip install mkdocs-material

pages:
  script:
  - mkdocs build
  - mv site public
  artifacts:
    paths:
    - public
  only:
  - master
```
